---
title: "VIZ part 2"
output: github_document
date: "2023-10-09"
---


```{r}
library(tidyverse)
library(patchwork)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

##same plot from last time 
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temparture Plot",
    x = "Min daily temp (Degrees c)",
    y = "M ax daily temp",
    color = "Location",
    caption = "max vs min daily temp in three locations; data from nrad"
  ) +
  scale_x_continuous(
  breaks = c(-15, 0, 15),
  labels = c("-15C", "0", "15")
  ) +
  scale_y_continuous(
    position = "right", 
    trans = "sqrt"
  )
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

##same plot from last time 
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temparture Plot",
    x = "Min daily temp (Degrees c)",
    y = "M ax daily temp",
    color = "Location",
    caption = "max vs min daily temp in three locations; data from nrad" ) +
      viridis::scale_color_viridis(discrete = TRUE)
    
```


```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temparture Plot",
    x = "Min daily temp (Degrees c)",
    y = "M ax daily temp",
    color = "Location",
    caption = "max vs min daily temp in three locations; data from nrad" ) +
      viridis::scale_color_viridis(discrete = TRUE) +
  theme_bw()
  theme(legend.position = "bottom") 
```

##data argumen

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth()


nyc_weather_df = 
  weather_df |> 
  filter(name == "CentralPark_NY")

hawaii_weather_df =
  weather_df |>
  filter(name == "Molokai_HI")

ggplot(nyc_weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = hawaii_weather_df)

```



## 'patchwork'

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() +
  facet_grid(. ~ name)
```


```{r}
ggp_temp_scatter = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5)

ggp_prcp_density = 
 weather_df |>
  ggplot(aes(x = prcp, color = name)) +
  geom_density()
```


```{r}
ggp_prcp_density =
  weather_df |>
  filter(prcp > 25) |>
  ggplot(aes(x = prcp, color = names)) +
  geom_density()
```

```{r}
ggp_temp_scatter + ggp_prcp_density
```















